Fixed two failing pdb-related tests on Python 3.13.
