ANSI escape codes for colored output now handled correctly in :func:`pytest.fail` with `pytrace=False`.
